# .chglog/config.yml
repository_url: https://github.com/cmssantos/aspnetcore-jsonlocalizer

# Template padrão para o changelog
template: |
  # Changelog

  {{ range .Versions }}
  ## [{{ .Version }}] - {{ .Date.Format "2006-01-02" }}
  {{ range .Commits }}
  - {{ .Subject }}
  {{ end }}
  {{ end }}
