name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests with Coverage
        run: |
          dotnet test ./tests/Cms.AspNetCore.JsonLocalizer.Tests \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=./TestResults/

      - name: Upload cobertura coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./tests/Cms.AspNetCore.JsonLocalizer.Tests/TestResults/coverage.*.cobertura.xml

      - name: Send coverage to Codacy
        run: |
          curl -Ls https://coverage.codacy.com/get.sh > codacy-coverage-reporter.sh
          chmod +x codacy-coverage-reporter.sh
          ./codacy-coverage-reporter.sh report \
            --language csharp \
            --coverage-reports ./tests/Cms.AspNetCore.JsonLocalizer.Tests/TestResults/coverage.net8.0.cobertura.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
