name: Release Package

on:
  push:
    tags:
      - 'v*'   # qualquer tag começando com "v"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Extract version info
        id: version
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

          if [[ "${TAG_NAME}" == *-* ]]; then
            VERSION_SUFFIX="${TAG_NAME#*-}"
          else
            VERSION_SUFFIX=""
          fi
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

          VERSION_BASE="${TAG_NAME#v}"
          VERSION_BASE="${VERSION_BASE%%-*}"
          echo "VERSION_BASE=$VERSION_BASE" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: |
          if [ -z "$VERSION_SUFFIX" ]; then
            dotnet pack --configuration Release --no-build --output ./artifacts /p:PackageVersion=$VERSION_BASE
          else
            dotnet pack --configuration Release --no-build --output ./artifacts /p:PackageVersion=$VERSION_BASE --version-suffix $VERSION_SUFFIX
          fi

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Push NuGet package
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
